```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
PA=(35+sample(8,1))/100
PB=(40+sample(8,1))/100
PAOrB=(75-sample(8,1))/100
## QUESTION/ANSWER GENERATION
questions <- character(5)
    questions[1] <- PA+PB-PAOrB
    questions[2] <- round(PA*PB,4)
    questions[3] <- PA+PB
    questions[4] <- round(PA+PB-PA*PB,4)
    questions[5] <- "impossible to determine from the given information"

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

If $P(A) = `r PA`$, $P(B) = `r PB`$ and $P(A \mbox{ or } B)= `r PAOrB`$, then $P(A \mbox{ and } B)$ is...


```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

We can use the formula $P(A \mbox{ or } B) = P(A) + P(B) - P(A \mbox{ and } B)$ for this one. Rearranging
gives $P(A \mbox{ and } B) = P(A) + P(B) - P(A \mbox{ or } B)$, or in RStudio:

```{r}
PA + PB - PAOrB
```

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
