```{r data generation, echo = FALSE, results = "hide"}
## QUESTION/ANSWER GENERATION
questions <- character(5)
questions[1] <- "1"
questions[2] <- "0"
questions[3] <- "2"
questions[4] <- "any value between 1 and 2"
questions[5] <- "any positive value"

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

The probability of an event $A$ and the probability of its complement $A'$ always sum to

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

An event and it's complement are mutually exclusive and cover all options so must sum to 1.

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice