```{r data generation, echo = FALSE, results = "hide"}
## QUESTION/ANSWER GENERATION
questions <- character(5)
    questions[1] <- "An $\\bar{x}$ chart is used to
control the process mean whereas a $R$ chart is
used to control the process variation."
    questions[2] <- "The 3-sigma control limits for the
$\\bar{x}$ chart are $\\bar{\\bar{x}} \\pm
3\\sigma / \\sqrt n$ where $n$ is the total
number of units being inspected."
    questions[3] <- "If both mean $\\mu$ and variation
$\\sigma$ are unknown and we are unsure if the
process variation is stable, one should construct an
$\\bar{x}$ chart prior to a $R$
chart."
    questions[4] <- "An $\\bar{x}$ chart is a variable
control chart and a $R$ chart is an attribute
control chart."
    questions[5] <- "The $\\bar{x}$ and
$R$ charts are old fashioned, so we must use 
$\\bar{x}$ and $s$ charts instead."

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- "Correct"
explanations[2] <- "The limits are defined in terms of $\\bar{R}$ and some control chart constants."
explanations[3] <- "Attribute control charts are for defects. The $R$ chart is for process variation for a measurement variable."
explanations[4] <- "The $R$ chart should come before the $\\bar{x}$ chart."
explanations[5] <- "Both $R$ and $s$ charts are useful for process variation."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following statements concerning the $\bar{x}$ and $R$ charts is true?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
