```{r data generation, echo = FALSE, results = "hide"}
library(exams)
## QUESTION/ANSWER GENERATION
questions <- character(5)
questions[1] <- "The theorem says that the sampling distribution of $\\bar{x}$ can be approximated by a normal distribution with mean $\\mu$ and standard deviation $\\frac{\\sigma}{\\sqrt{n}}$ when the sample size $n$ is large, irrespective of the shape of the population distribution."
questions[2] <- "The theorem is valid only when the population follows
a normal distribution."
questions[3] <- "The sample size $n = 30$ is always
large enough for us to apply the theorem."
questions[4] <- "For highly skewed distribution, a small value of
$n$ will suffice to invoke the theorem."
questions[5] <- "The theorem is of limited use, since we often do not
know the population's mean or variance."

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- "There is no requirement for the population to follow a normal distribution."
explanations[3] <- "The size of sample required depends on how non-normal the population is."
explanations[4] <- "For a highly skew distribution we'll need a larger value of $n$."
explanations[5] <- "A key point of the CLT is that it allows us to estimate the unknown population mean."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following statements is true when considering the Central Limit Theorem?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
