```{r data generation, echo = FALSE, results = "hide"}
## QUESTION/ANSWER GENERATION
questions <- character(5)
questions[1] <- "The Central Limit Theorem."
questions[2] <- "The Mean Value Theorem."
questions[3] <- "The Normal Distribution Theorem."
questions[4] <- "The Binomial Theorem."
questions[5] <- sample(c("Fermat's Last Theorem.", "The Fundamental Theorem of Algebra.", "The Approximation Theorem.", "The Fundamental Theorem of Calculus.", "The Pythagorean Theorem."),1)


solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Let $\{x_1, x_2, \ldots, x_n\}$  be a random
sample from a distribution with mean $\mu$ and standard deviation
$\sigma$. If $n$ is sufficiently large, the sample mean $\bar{x}$
has an approximately normal distribution. This result is known as the

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
