```{r data generation, echo = FALSE, results = "hide"}
## QUESTION/ANSWER GENERATION
questions <- character(5)
questions[1] <- "Binomial distribution."
questions[2] <- "Exponential distribution."
questions[3] <- "Poisson distribution."
questions[4] <- "Normal distribution."
questions[5] <- "Uniform distribution."

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- "The draws with replacement are likely independent, and the probability of a red will be the same each time. So we have a fixed number of repeat, independent, binary events."
explanations[2] <- "The exponential distribution models the time to event, where events occur at a given rate."
explanations[3] <- "The Poisson distribution models the number of events in a given period, given that the events occur independently at a given rate."
explanations[4] <- "The Normal distribution describes continuous measures."
explanations[5] <- "The uniform distribution describes a continuous measure that has the same chance of taking any value in a particular interval."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

A box contains 60 red and 40 blue marbles.
Marbles are drawn one at a time from the box, at random with
replacement. Let $X$ be number of red marbles in $5$ draws. What
distribution does $X$ have?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
