```{r data generation, echo = FALSE, results = "hide"}
## QUESTION/ANSWER GENERATION
questions <- character(5)
questions[1] <- "Students' marks in a multiple choice exam with 20 questions."
questions[2] <- "The weights of crates of apples."
questions[3] <- "The times taken to complete a clerical task."
questions[4] <- "The costs of 1 litre of milk in a survey of 100 countries."
questions[5] <- "The greatest speed you and your classmates have ever travelled in a car."

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- "The student marks can only take the values 0/20, 1/20, ... 20/20, so are discrete."
explanations[2] <- "Weights are continuous measures."
explanations[3] <- "Times are continuous measures."
explanations[4] <- "Costs of milk across many countries are likely continuous, as exchange rates are continuous."
explanations[5] <- "Speeds are generally continuous."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following variables is most likely not to have a continuous
distribution?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
