```{r data generation, echo = FALSE, results = "hide"}
library(masseystat)
# created MBJ, confirmed JG

lambda<-round(abs(rnorm(1,0,2)),2)
x<-round(abs(rnorm(1,0,0.5)),2)

## QUESTION/ANSWER GENERATION
questions <- numeric(5)
questions[1] <- signif(pexp(x,lambda, lower=FALSE),3)
questions[2] <-   signif(pexp(x,lambda, lower=FALSE )-.05,3)
questions[3] <-  signif(pexp(x, lambda ),3)
questions[4] <-   signif(pexp(x,lambda, lower=FALSE )*1.1,3)
questions[5] <-   signif(pexp(x,lambda, lower=FALSE )+.05,3)

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
questions <- make_unique(questions, solutions, tolerance=0.01)
questions <- as.character(questions)

explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

$X$ has an exponential distribution with rate `r lambda`.  What is
the probability that $X$ is greater than `r x`?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

Noting that $P(X > x) = 1 - P(X < x)$ we can use <code>1 - pexp(`r x`, rate=`r lambda`)</code>, or alternatively, <code>pexp(`r x`, rate=`r lambda`, lower.tail=FALSE)</code>

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
