```{r data generation, echo = FALSE, results = "hide"}
library(exams)
## DATA GENERATION
## QUESTION/ANSWER GENERATION
questions <- character(5)
questions[1] <- "$P(A \\cup B)\\le P(A)+P(B)$."
questions[2] <- "$P(A \\cap B)=P(A) \\times P(B)$."
questions[3] <- "$P(A \\cup B)=P(A)+P(B)$."
questions[4] <- "$P(A \\cap B)> P(A)$."
questions[5] <- "$P(A \\cup B)< P(B)$."

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- "Yes, as $P(A \\cap B) \\ge 0.$"
explanations[2] <- "Only if $A$ and $B$ are independent."
explanations[3] <- "Only if $P(A \\cap B) = 0$, i.e. the events are disjoint."
explanations[4] <- "$P(A \\cap B) \\le P(A)$, as requiring $B$ to occur as well as $A$ is more stringent."
explanations[5] <- "$P(A \\cup B) \\ge P(B)$, as giving the option for $B$ to occur instead of $A$ is less stringent."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```


Question
========

Which of the following probability expressions is **always** true?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

Recall that $P(A \cup B) = P(A) + P(B) - P(A \cap B)$.

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
