```{r data generation, echo = FALSE, results = "hide"}
questions <- character(5)
    questions[1] <- "The 75$^{th}$ percentile is approximately .67"
    questions[2] <- "The 90$^{th}$ percentile is approximately --- 1.28"
    questions[3] <- "The 10$^{th}$ percentile is approximately 1.28"
    questions[4] <- "The 15$^{th}$ percentile is approximately 1.04"
    questions[5] <- "The difference between the 10$^{th}$  and 20$^{th}$  percentiles is the same as the difference between the 20$^{th}$  and 30$^{th}$  percentiles."

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following statements about the percentiles for the standard normal distribution is correct? 

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

We can use the `qnorm` function to compute quantiles. e.g.

```{r}
qnorm(c(0.1, 0.15, 0.2, 0.3, 0.75, 0.9))
```

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
