```{r data generation, echo = FALSE, results = "hide"}
library(exams)

Mean=900+sample(200,1)
SD=790+sample(20,1)
## QUESTION/ANSWER GENERATION
questions <- character(5)
    questions[1] <- round(Mean+1.645*SD,0)
    questions[2] <- round(Mean+3*SD,0)
    questions[3] <- round(Mean+2*SD,0)
    questions[4] <- round(Mean+SD,0)
    questions[5] <- round(Mean+1.5*SD,0)
    solutions <- c(TRUE,FALSE, FALSE, FALSE, FALSE)

explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

The $95^{th}$ percentile of a normal distribution with $\mu=`r Mean`$ and $\sigma=`r SD`$ is closest to...

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

We can use the `qnorm` function to find quantiles or percentiles, so can use <code>qnorm(0.95, mean = `r Mean`, sd = `r SD`)</code>.

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
