```{r data generation, echo = FALSE, results = "hide"}
## QUESTION/ANSWER GENERATION
questions <- character(5)
    questions[1] <- "The data follow a normal distribution."
    questions[2] <- "The data might follow an exponential distribution."
    questions[3] <- "The data always follow a uniform distribution."
    questions[4] <- "The data can never follow a normal distribution."
    questions[5] <- "The data follow a Weibull distribution."

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- "Yes, a straight line on a normal probability plot suggests a normal distribution."
explanations[2] <- "No, data from the exponential distribution is not straight on a normal probability plot."
explanations[3] <- "No, data from a uniform distribution will not be straight on a normal probability plot."
explanations[4] <- "If the line is straight, then a normal distribution is plausible."
explanations[5] <- "No, data from a Weibull distribution will not be straight on a normal probability plot."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

The overall pattern of `r sample(20,1)+15` points on a normal probability plot is a straight line. This pattern indicates that

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
