```{r data generation, echo = FALSE, results = "hide"}
questions <- character(5)
    questions[1] <- "The 80$^{th}$ percentile is the same as the 0.20$^{th}$ quantile."
    questions[2] <- "The 50$^{th}$ percentile is equal to the mean."
    questions[3] <- "The 90$^{th}$ percentile is about 1.28 standard deviations above the mean."
    questions[4] <- "The 10$^{th}$ percentile is about 1.28 standard deviations below the mean."
    questions[5] <- "The 0.975$^{th}$ quantile is a little less than two standard deviations above the mean."

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following statements are **not** true for a normal
distribution with mean $\mu$ and standard deviation $\sigma$?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

We can check percentiles (or quantiles) using the `qnorm()` function in R. e.g.

```{r}
qnorm(0.5)
qnorm(0.9)
qnorm(0.1)
qnorm(0.975)
qnorm(0.2) == qnorm(0.8)
```

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
