```{r data generation, echo = FALSE, results = "hide"}
library(exams)
## QUESTION/ANSWER GENERATION
questions <- character(5)
questions[1] <- "A standard normal distribution."
questions[2] <- "Any normal distribution."
questions[3] <- "A Poisson distribution."
questions[4] <- "An exponential distribution."
questions[5] <- "A binomial distribution."
solutions <- c(FALSE, FALSE, FALSE,TRUE,FALSE)

explanations <- character(5)
explanations[1] <- "Data from a normal distribution will follow a straight line."
explanations[2] <- "Data from a normal distribution will follow a straight line."
explanations[3] <- "Data from a Poisson distribution might follow a straight line if the rate $\\lambda$ is high enough."
explanations[4] <- "Data from an exponential distribution is always skew, so non-normal."
explanations[5] <- "Data from a binomial distribution might follow a straight line if $n$ is large enough, e.g. so that $np > 5$, $n(1-p) > 5$."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

The general layout of a set of `r 12+sample(10,1)`  points on a normal probability plot is approximately following a straight line. This pattern tells us (among other things) that the data cannot possibly come from...

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
