```{r data generation, echo = FALSE, results = "hide"}
library(masseystat)
# created MBJ, confirmed JG

lambda<-round(abs(rnorm(1,3,2)),2)
x<-rpois(1, lambda)+1

## QUESTION/ANSWER GENERATION
questions <- numeric(5)
questions[1] <- round(dpois(x, lambda),4)
questions[2] <- round(ppois(x, lambda), 4)
questions[3] <-  round(dpois(x, lambda)+0.05, 4)
questions[4] <-  round(dpois(x, lambda)-0.05, 4)
questions[5] <-   round(dpois(x,lambda)/(1-dpois(0, lambda)), 4)

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
questions <- make_unique(questions, solutions, tolerance=0.01)
questions <- as.character(questions)

explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

$X$ has a Poisson distribution with rate `r lambda`.  Find the probability that $X=`r x`$.

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

For the probability that $X$ is equal to `r x` we use `dpois`: <code>dpois(`r x`, lambda=`r lambda`)</code>.

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
