```{r data_generation, echo=FALSE, results='hide'}
library(exams)

questions <- character(5)
    questions[1] <- "The value of *r* depends on which of the two
variables under study is labeled *x* and which is
labeled *y*."
    questions[2] <- "The value of *r* is independent of the units in
which *x* and *y* are measured."
    questions[3] <- "The value of *r* is always between -1 and +1,
inclusive."
    questions[4] <- "The value of *r* is 1 if all $(x_i ,y_i
)$ pairs lie on a straight line with positive slope."
    questions[5] <- "The value of *r* is -1 if all $(x_i ,y_i
)$ pairs lie on a straight line with negative slope."

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- "The correlation coefficient is symmetric in *x* and *y*"
explanations[2] <- "The correlation coefficient does not change when the units of *x* or *y* change."
explanations[3] <- "The correlation coefficient is no lower than -1 and no higher than 1."
explanations[4] <- "A correlation of 1 means perfect positive correlation, so all points lie on an increasing line."
explanations[5] <- "A correlation of -1 means perfect negative correlation, so all points lie on a decreasing line."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following statements is **NOT** true about the sample correlation coefficient *r*?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
