
```{r data generation, echo = FALSE, results = "hide"}

questions <- character(5)
    questions[1] <- "`geom_point()`."
    questions[2] <- "`geom_smooth()`."
    questions[3] <- "`geom_density2d()`."
    questions[4] <- "All of the above."
    questions[5] <- "A and B above."

solutions <- c(FALSE,FALSE,FALSE,TRUE,FALSE)
explanations <- rep("All of `geom_point()`, `geom_smooth()` and `geom_density2d()` are options for two numeric variables.", 5)

# permute order of solutions/questions
Order <- c(sample(1:3),4,5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========
Suppose you have two continuous numeric variables. Which of the following `ggplot2` layers might be appropriate?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple choice
