```{r, echo=FALSE, results = "hide"}
library(ggplot2)
## QUESTION/ANSWER GENERATION
N=33+sample(10,1)
Min=20+sample(5,1)
Scalar=5+sample(4,1)
dataX=data.frame(X=round(Min + Scalar*runif(N), 2))
TheIQR=IQR(dataX$X)

Drop=1+sample(5,1)
questions <- character(6)
questions[1] <- round(TheIQR,2)
questions[2] <- round(0.7*TheIQR,2)
questions[3] <- round(0.5*TheIQR,2)
questions[4] <- round(1.2*TheIQR,2)
questions[5] <- round(1.75*TheIQR,2)
questions[6] <- round(1.5*TheIQR,2)

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- rep("The interquartile range is the length of the box in a boxplot.", 5)

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

The following boxplot shows the estimated amount of carbon monoxide in `r N` air samples.

```{r, echo=FALSE, fig.height=2, fig.width=7, fig.cap="", fig.retina=2}
ggplot(dataX) + 
  geom_boxplot(aes(x=X)) +
  labs(x="Carbon monoxide")
```

What is the best estimate for the inter-quartile range?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple choice
