```{r, echo=FALSE, results = "hide"}
questions <- character(5)
questions[1] <- "Trimmed mean."
questions[2] <- "Standard deviation."
questions[3] <- "Range."
questions[4] <- "Inter-quartile range."
questions[5] <- "Variance."
solutions <- c(TRUE, FALSE, FALSE, FALSE, FALSE)

explanations <- character(5)
explanations[1] <- "This is a measure of centre or location."
explanations[c(2:5)] <- "This is definitely a measure of variability in data."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following is **not** a measure of variability of data?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple choice
