```{r data_generation, echo=FALSE, results='hide'}
library(exams)

questions <- character(5)
questions[1] <- "Linearity"
questions[2] <- "Normality"
questions[3] <- "Independence"
questions[4] <- "Equal variance"
questions[5] <- "Heteroscedasticity"

solutions <- c(FALSE,FALSE,FALSE,FALSE,TRUE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- "Heteroscedasticity means unequal variance."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following statements is not an assumption of the linear model?
  
```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

The linear model assumptions are **L**inearity, **I**ndependence, **N**ormality and **E**qual variance (homoscedasticity). You can remember these via the LINE mnemonic.

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
  
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
