
```{r data_generation, echo=FALSE, results='hide'}
library(exams)

questions <- character(5)
questions[1] <- "90% of the *y* values fall into the 95% prediction interval."
questions[2] <- "90% of the variation in *y* can be explained by the regression line."
questions[3] <- "90% of the *y* values fall into the 90% confidence interval."
questions[4] <- "90% of the variation in x can be explained by regression line"
questions[5] <- "We have 90% confidence in that the variation of *y* is explained by the fitted linear model."


solutions <- c(FALSE,TRUE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- "A 95% prediction interval should capture 95% of *y* values, regardless of $R^2$ (assuming the linear model assumptions hold)."
explanations[2] <- "Yes. The coefficient of variation is essentially $\\frac{\\mbox{variation explained}}{\\mbox{total variation}}$."
explanations[3] <- "90% of *y* values will fall in a 90% prediction interval (regardless of $R^2$)."
explanations[4] <- "It is the variation in *y* that is explained by the regression model."
explanations[5] <- "There'll always be some variation in *y* that can't be explained by the fitted linear model. $R^2$ tells us how much is explained."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

In a regression problem, if the coefficient of determination ($R^2$) is 0.90, this means that:
  
```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
