
```{r data_generation, echo=FALSE, results='hide'}
library(exams)

questions <- character(5)
questions[1] <- "regression coefficient"
questions[2] <- "residual standard error"
questions[3] <- "standard error of estimated slope"
questions[4] <- "R-squared"
questions[5] <- "t value"

solutions <- c(FALSE,TRUE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========
  
The vertical spread of the data points about the regression line is measured by the:

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

Variation of data points around the regression line is the variations in
residuals (so standard error of residuals).

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
  
  extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice

