```{r data generation, echo = FALSE, results = "hide"}
library(tidyverse)
library(exams)

Linearity <- FALSE
EqualVar <- TRUE
n <- 100
d <- data.frame(x = sort(runif(n, -2, 2)))
a <- sample(c(0, 1), 1)
b <- sample(c(-1, 1), 1)
Var.Factor<-1
if(EqualVar==FALSE) Var.Factor <- (1:n)/20
e <- rnorm(n, sd = 0.25*Var.Factor)
d$y <- a + b * d$x + e 
if(Linearity==FALSE) d$y <- a + b *exp( d$x) + e 
m <- lm(y ~ x, data = d)

questions <- character(5)
questions[1] <- "Linearity"
questions[2] <- "Normality"
questions[3] <- "Independence"
questions[4] <- "Equal variance"
questions[5] <- "Linearity and equal variance"

solutions <- c(TRUE,FALSE,FALSE,FALSE,FALSE)

explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```    

Question
========

A simple linear model is fitted to `x` and `y` and the 4-in-1 residual diagnostics plot is presented as follows. 
```{r, echo=FALSE, fig.width=8, fig.height=5, fig.cap="", fig.retina=2}
par(mfrow=c(2,2), mar=c(4,4,2,2))
plot(m)
```

Which one of the following assumptions fails to hold based on the diagnostics plots?
  
```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
  extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice