```{r data_generation, echo=FALSE, results='hide'}
library(exams)

questions <- character(5)
questions[1] <- "The value of *b* depends on which of the two variables under study is labeled *x* and which is labeled *y*."
questions[2] <- "The value of *b* depends on the units in which *x* and *y* are measured."
questions[3] <- "The value of *b* is always between -1 and +1, inclusive."
questions[4] <- "*b* is called the slope or gradient in simple linear regression."
questions[5] <- "The sign of *b* is the same as the sign of correlation coefficient *r*."

solutions <- c(FALSE,FALSE,TRUE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========
  
Which of the following statements is **not true** about the regression coefficient *b*?
  
```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

The slope *b* can take any value. It is the correlation coefficient
that is restricted to -1 to 1.

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
  
  extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
