```{r data_generation, echo=FALSE, results='hide'}
library(exams)

questions <- character(5)
questions[1] <- "In a fixed design setting, *x* is fixed and *y* is random."
questions[2] <- "*x* is the independent variable and *y* is the dependent variable."
questions[3] <- "*x* is the dependent variable and *y* is the independent variable."
questions[4] <- "*x* is the explanatory variable and *y* is the response variable."
questions[5] <- "*x* is a covariate or a predictor and the mean of *y* can be predicted given *x*"

solutions <- c(FALSE,FALSE,TRUE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following statements is **not true** about *x* and *y* in simple linear regression?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

In simple linear regression $y = a + bx$, $x$ is independent, with $y$ dependent on $x$ (and the coefficients $a$ and $b$).

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
