```{r data_generation, echo=FALSE, results='hide'}
library(exams)

questions <- character(5)
questions[1] <- "If a linear function that is plotted on a graph passes through the origin of a graph, then *b* = 0."
questions[2] <- "If a regression line that was calculated by least squares is plotted on a scatter diagram, all of the points in the data set will be on the line."
questions[3] <- "Unexplained variation in the *x* variable is denoted *e*."
questions[4] <- "If least squares is used to estimate a linear function with an intercept, then the mean of the *e* will always be equal to zero."
questions[5] <- "If a two unit increase in the value of *x* results in a one unit decrease in the mean of *y*, then b = -2."

solutions <- c(FALSE,FALSE,FALSE,TRUE,FALSE)
explanations <- character(5)
explanations[1] <- "If the line passes through the origin, then the y-intercept is zero ($a=0$)."
explanations[2] <- "Typically the points will scatter around the line, not on the line, as there will be some variation in the values that $y$ takes around the modelled mean (the line)."
explanations[3] <- "Unexplained variation in the *y* variable is denoted using *e*."
explanations[4] <- "One way to see this is to recognise that the linear equation $y = a + bx$ is describing the mean of $y$ for changing $x$. By taking the mean
of this, we see that $\\bar{y} = a + b \\bar{x}$, so that $\\bar{y} - (a + b \\bar{x}) = 0$. This is just $\\bar{e} = 0$."
explanations[5] <- "A two unit increase in *x* yielding a one unit decrease in *y* means $b = -\\frac{1}{2}$."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

Which of the following statements is true about simple linear regression?
  
```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========
  
```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================

extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
