```{r data_generation, echo=FALSE, results='hide'}
library(exams)

questions <- character(6)
questions[1] <- "numerical"
questions[2] <- "quantitative"
questions[3] <- "qualitative"
questions[4] <- "factor"
questions[5] <- "nominal"
questions[6] <- "categorical"

solutions <- c(TRUE,TRUE,FALSE,FALSE,FALSE,FALSE)
explanations <- character(6)
explanations[1] <- ""
explanations[2] <- ""
explanations[3] <- ""
explanations[4] <- ""
explanations[5] <- ""
explanations[6] <- ""

## permute order of solutions/questions
Order <- sample(c(sample(which(solutions==TRUE),1),3:6))
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========

The response variable *y* in a linear model can be 

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========

The response variable must be numeric (quantitative) as it is the result of a linear predictor equation.
  
```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
  
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice
