
```{r data_generation, echo=FALSE, results='hide'}
library(exams)

questions <- character(5)
questions[1] <- "Hourly electricity usage of a NZ household has a frequency of 24 over one day."
questions[2] <- "The time between successive eruptions from the Taupo volcano is a time series."
questions[3] <- "The population of NZ has a frequency of 1 over one year."
questions[4] <- "Time series data usually violate the assumption of independence for linear models."
questions[5] <- "A time series with both trend and seasonal effects can be fitted by linear models."

solutions <- c(FALSE,TRUE,FALSE,FALSE,FALSE)
explanations <- character(5)
explanations[1] <- "This makes sense as electricity usage will be roughly the same per hour for each week day."
explanations[2] <- "The time between successive eruptions is not collected regularly over time."
explanations[3] <- "This makes sense as population is unlikely to be seasonal."
explanations[4] <- "Time series data are very often correlated in time, so residuals are unlikely to be independent."
explanations[5] <- "We can easily put different components into a linear model such as trend or seasonality."

## permute order of solutions/questions
Order <- sample(1:5)
questions <- questions[Order]
solutions <- solutions[Order]
explanations <- explanations[Order]  
```

Question
========
  
Which one of the following statements is **not** true for time series.

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```

Solution
========
  
```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(mchoice2text(solutions, markup="markdown"), explanations, markup = "markdown")
```

Meta-information
================
  
extype: schoice
exsolution: `r mchoice2string(solutions)`
exname: Multiple Choice

